### ISSUE TITLE
When the parameter is three slashes ("/"), it will return undefined.

### ISSUE THREAD

**Issue by houyonglu** [jfromaniello/url-join#111] opened 2024-06-02 16:37 UTC
Version 5.0.0
```js
var urlJoin = require('url-join');
var joinedUrl = urlJoin('/', '/', '/');
console.log(joinedUrl);  // => undefined
```

Expected output: `/`
Actual output: `undefined`

**Comment by pano9000** [comment] 2024-06-20 11:38
I cannot reproduce this on my end with v5.0.0 on node 21.6.2
```
const urlJoin = await import("url-join");
let joinedUrl = urlJoin.default("/", "/", "/");
console.log(`Output: '${joinedUrl}'`);
```
=> prints `Output: '//'`

I do not get `undefined` but `//` as return value

**Comment by houyonglu** [comment] 2024-06-21 12:44
Hi there, I sincerely apologize for opening this issue without being able to reproduce it. I assumed I was using the latest version of the library with a default install, but I failed to check the actual version in the lock file. As I didn't commit any changes, I can't determine the exact version used at the time.  
I should have tried to reproduce the issue in a minimal implementation before opening an issue, but I didn't. I am truly sorry for the inconvenience.

**Comment by jonkoops** [comment] 2024-06-24 10:50
Since this issue is not reproducible I will go ahead and close it, feel free to report a new issue if this is somehow reproducible in the latest version.

**Closed as not planned by jonkoops** 2024-06-24 10:50 UTC
Labels: bug
