### ISSUE TITLE
Slash disappears

### ISSUE THREAD

**Issue by roboxv** [jfromaniello/url-join#41] opened 2018-05-06 13:58 UTC
Hello.

`urlJoin(['http://example.com/', 'api/products/?offset=200'])`
gives me:
`'http://example.com/api/products?offset=200'`
instead of 
`'http://example.com/api/products/?offset=200'`

**Comment by caseyjhol** [comment] 2018-05-10 22:37
Duplicate of #10.

**Comment by jonkoops** [comment] 2022-05-27 12:59
Duplicate of #10

**Closed by jonkoops** 2022-05-27 12:59 UTC
